### ISSUE TITLE
Unable to register. Please try again.

### ISSUE THREAD

**Issue by devburaq** [yurineves92/login-register-php#1]
I get this error on registration
https://pasteboard.co/JpYF11k.png

**Comment by yurineves92** [comment]
@mburakolgun 
I'll check this out for you.

**Comment by yurineves92** [comment]
Correction in line 92 of the user.php file inside the objects folder

![image](https://user-images.githubusercontent.com/9011206/92404290-882ef580-f109-11ea-899e-dd22098de945.png)

**Comment by yurineves92** [comment]
@mburakolgun 

Please, as soon as you test update your branch and get the new updates do the test. As soon as it is functional please let me know to close the issue as resolved.

**Comment by devburaq** [comment]
Add this code to line 106 :) it worked smoothly now. Thank you.

$this->access_code = htmlspecialchars(strip_tags($this->access_code));
